spring:
  application:
    name: moviehub
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active:
    - dev

tmdb:
  api:
    key: ${TMDB_API_KEY:CHAVE_AQUI} Coloque sua chave aqui ou via variável de ambiente
    base-url: https://api.themoviedb.org/3
    language: pt-BR

server:
  port: 8080

logging:
  level:
    net.ddns.adambravo79.moviehub.client: TRACE
    org.springframework.cloud.openfeign: TRACE